In [1]:
import gym
env = gym.make("CartPole-v1")
observation = env.reset()
for _ in range(10000):
    env.render()
    action = env.action_space.sample() # your agent here (this takes random actions)
    observation, reward, done, info = env.step(action)
    print(observation, done)
    
    if done:
        observation = env.reset()
env.close()

[-0.02876905 -0.17015201  0.00248349  0.30186642] False
[-0.03217209  0.02493446  0.00852082  0.00996777] False
[-0.0316734  -0.17030865  0.00872018  0.30532689] False
[-0.03507957  0.02468795  0.01482671  0.0154068 ] False
[-0.03458581  0.21959417  0.01513485 -0.27256149] False
[-0.03019393  0.02425957  0.00968362  0.02485633] False
[-0.02970874 -0.17099991  0.01018075  0.32057875] False
[-0.03312874  0.02397559  0.01659232  0.03112375] False
[-0.03264923 -0.17138033  0.0172148   0.32899521] False
[-0.03607683  0.02349238  0.0237947   0.04179036] False
[-0.03560699  0.21826518  0.02463051 -0.24329116] False
[-0.03124168  0.02280023  0.01976468  0.05705797] False
[-0.03078568  0.2176333   0.02090584 -0.22932411] False
[-0.02643301  0.02221894  0.01631936  0.06987926] False
[-0.02598863 -0.17313313  0.01771695  0.36766602] False
[-0.02945129  0.02173264  0.02507027  0.08062174] False
[-0.02901664  0.21648641  0.0266827  -0.20404722] False
[-0.02468691  0.02099323  0.02260176  0.09693194

KeyboardInterrupt: 

In [ ]:
import gym
env = gym.make("Hand-v1")
observation = env.reset()
for _ in range(10000):
    env.render()
    action = env.action_space.sample() # your agent here (this takes random actions)
    observation, reward, done, info = env.step(action)
    print(observation, done)
    
    if done:
        observation = env.reset()
env.close()

In [1]:
import numpy as np
import gym


env = gym.make("HandReach-v0")
obs = env.reset()
done = False

def policy(observation, desired_goal):
    # Here you would implement your smarter policy. In this case,
    # we just sample random actions.
    return env.action_space.sample()

while not done:
    action = policy(obs["observation"], obs["desired_goal"])
    obs, reward, done, info = env.step(action)

    # If we want, we can substitute a goal here and re-compute
    # the reward. For instance, we can just pretend that the desired
    # goal was what we achieved all along.
    substitute_goal = obs["achieved_goal"].copy()
    substitute_reward = env.compute_reward(
        obs["achieved_goal"], substitute_goal, info)
    print("reward is {}, substitute_reward is {}".format(
        reward, substitute_reward))

DependencyNotInstalled: No module named 'mujoco_py'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)